# cl65 -c ignores -o; compile with cc65 then ca65.

CUSTOM_RULE_C_TO_OBJECTDIR_O = 1
$(OBJECTDIR)/%.o: %.c | $(OBJECTDIR)
	$(TRACE_CC)
	$(Q)$(CC65_HOME)/bin/cc65 $(CFLAGS) -o $(OBJECTDIR)/$*.s $<
	$(Q)$(AS) $(ASFLAGS) -o $@ $(OBJECTDIR)/$*.s
	$(Q)rm -f $(OBJECTDIR)/$*.s

CUSTOM_RULE_S_TO_OBJECTDIR_O = 1
$(OBJECTDIR)/%.o: %.S | $(OBJECTDIR)
	$(TRACE_AS)
	$(Q)$(AS) $(ASFLAGS) -o $@ $<

CUSTOM_RULE_C_TO_CO = 1
%.co: %.c
	$(TRACE_CC)
	$(Q)$(CC65_HOME)/bin/cc65 $(CFLAGS) -DAUTOSTART_ENABLE -o $*.s $<
	$(Q)$(AS) $(ASFLAGS) -o $@ $*.s
	$(Q)rm -f $*.s

CUSTOM_RULE_LINK = 1
$(OBJECTDIR)/crt0.o: $(RELAY65_CRT0) | $(OBJECTDIR)
	$(TRACE_AS)
	$(Q)$(AS) $(ASFLAGS) -o $@ $<

$(OBJECTDIR)/write.o: $(RELAY65_WRITE) | $(OBJECTDIR)
	$(TRACE_AS)
	$(Q)$(AS) $(ASFLAGS) -o $@ $<

%.$(TARGET): %.co $(PROJECT_OBJECTFILES) $(PROJECT_LIBRARIES) contiki-$(TARGET).a $(OBJECTDIR)/crt0.o $(OBJECTDIR)/write.o
	$(TRACE_LD)
	$(Q)$(CC65_HOME)/bin/ld65 -C $(RELAY65_CFG) -o $@ \
	  $(OBJECTDIR)/crt0.o $(OBJECTDIR)/write.o $*.co \
	  $(PROJECT_OBJECTFILES) contiki-$(TARGET).a \
	  $(CC65_HOME)/lib/none.lib
